name = "personal-site"

[node]
compatibility_date = "2025-01-20"  # Update this to the date you're deploying
compatibility_flags = []          # Optional, additional compatibility flags
node_version = "20.10.0"           # Specify the Node.js version you want