name = "personal-site" # Optional for Pages
type = "javascript"        # Optional for Pages (can also be "rust" or "webpack")

[site]
bucket = "./out"           # Path to the output directory
entry-point = "workers-site" # Defaults to "workers-site" for Workers Sites

# Pages-specific configuration
[pages]
pages_build_output_dir = "out" # Replace "out" with your build output directory

# Optional Node.js settings if you're using Workers
[node]
compatibility_date = "2025-01-20" # Date of compatibility for the runtime
node_version = "20.10.0"           # Node.js version